public  class StudentMarksheet {
    public void showMarksheetUsingDatatype (){
        String firstName = 'Akif';
        String lastName = 'DOGAN';
        String mathematics = 'a+';
        String english = 'f-';
        String chemistry = 'd+';
        System.debug('my first name = '+ firstName);
        System.debug('my last name = '+ lastName);
        System.debug('my mathematics grade = '+ mathematics);
        System.debug('my english grade = '+ english);
        System.debug('my chemistry grade = '+ chemistry);
    }  
    public void showMarksheetUsingObject(){
        Object firstName = 'Akif';
        object lastName = 'DOGAN';
        object mathematics = 'a+';
        object english = 'f-';
        object chemistry = 'd+';
        System.debug('my first name = '+ firstName);
        System.debug('my last name = '+ lastName);
        System.debug('my mathematics grade = '+ mathematics);
        System.debug('my english grade = '+ english);
        System.debug('my chemistry grade = '+ chemistry);
    }    

}
