DmlDemo.dmlUpdateMultiple_right();
DmlDemo.dmlInsertMultiple_right();
DmlDemo.dmlInsertDemo_stndObj();
DmlDemo.dmlInsertDemo_cstmObj();
DmlDemo.dmlUpdateDemo_1();
DmlDemo.dmlUpdateDemo_3();
DmlDemo.dmlInsertDemo_4();
DmlDemo.dmlInsertDemo_5();
dmldemo.dmlInsertMultiple_right();
DmlDemo.dmlInsertMultiple_right2();
DmlDemo.dmlUpdateMultiple_right();

delete [select id from account where createddate = THIS_WEEK]; 

